on:
   push:
     branches:    
      - master

- name: Login to docker hub
  uses: actions-hub/docker/login@master
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

- name: Build :swarm-dev
  run: docker build -t swarm-dev:latest swarm-dev/

- name: Push to docker hub :latest
  uses: actions-hub/docker@master
  with:
    args: push swarmdisc/swarm-dev:latest
