name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      if: success()
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build :swarm-dev
      if: success()
      run: docker build swarm-dev/ --tag swarm-dev:$(date +%s)
    - name: Push to docker hub
      uses: actions-hub/docker@master
      with:
        args: push swarmdisc/swarm-dev:$(date +%s)
