name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_swarm-dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      if: success()
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image :swarm-dev
      if: success()
      run: docker build swarm-dev/ --tag swarmdisc/swarm-dev:latest
    - name: Push to docker hub
      uses: actions-hub/docker@master
      with:
        args: push swarmdisc/swarm-dev:latest)

  build_pangeo-swarm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      if: success()
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image :pangeo-swarm
      if: success()
      run: docker build pangeo-swarm/ --tag swarmdisc/pangeo-swarm:latest
    - name: Push to docker hub
      uses: actions-hub/docker@master
      with:
        args: push swarmdisc/pangeo-swarm:latest

  build_swarm-dashboards:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      if: success()
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image :swarm-dashboards
      if: success()
      run: docker build swarm-dashboards/ --tag swarmdisc/swarm-dashboards:latest
    - name: Push to docker hub
      uses: actions-hub/docker@master
      with:
        args: push swarmdisc/swarm-dashboards:latest
